#!/usr/bin/env python3
# /// script
# requires-python = ">=3.8"
# dependencies = []
# ///
"""Validate files generated by cli-agent-report mode=all.

The checks here intentionally focus on report-contract failures that are easy to
miss during manual generation, especially social post templates.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

MIN_PYTHON = (3, 8)

REQUIRED_REPORT_FILES = [
    "README.md",
    "report-index.md",
    "report-issues.md",
    "report-runtime.md",
    "report-agent-dev.md",
    "report-dev.md",
    "linkedin.md",
    "x.md",
    "findings.md",
]

PLACEHOLDER_RE = re.compile(r"\{\{[A-Z0-9_]+\}\}")
FINDING_ROW_RE = re.compile(
    r"^\|\s*§(\d+)\s*\|\s*([^|]+?)\s*\|\s*(Critical|High|Medium)\s*\|\s*([0-3?])/3\s*\|",
    re.MULTILINE,
)


def require_supported_python() -> None:
    if sys.version_info < MIN_PYTHON:
        required = ".".join(str(part) for part in MIN_PYTHON)
        current = ".".join(str(part) for part in sys.version_info[:3])
        print(
            f"validate_report_bundle.py requires Python {required}+; current Python is {current}",
            file=sys.stderr,
        )
        sys.exit(2)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate cli-agent-report mode=all artifacts."
    )
    parser.add_argument("evaluation_dir", help="Path to evaluations/<cli>")
    parser.add_argument(
        "--cli",
        help="Expected CLI/report name. Defaults to the evaluation directory name.",
    )
    return parser.parse_args(argv)


def read_text(path: Path, errors: list[str]) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        errors.append(f"missing required file: {path}")
    except UnicodeDecodeError as exc:
        errors.append(f"file is not valid UTF-8: {path}: {exc}")
    return ""


def finding_counts(findings_text: str) -> tuple[int, int, int, int, float | None]:
    pass_count = partial_count = fail_count = indeterminate_count = total_score = scored = 0
    for match in FINDING_ROW_RE.finditer(findings_text):
        score_text = match.group(4)
        if score_text == "?":
            indeterminate_count += 1
            continue
        score = int(score_text)
        total_score += score
        scored += 1
        if score == 3:
            pass_count += 1
        elif score == 0:
            fail_count += 1
        else:
            partial_count += 1
    average = round(total_score / scored, 1) if scored else None
    return pass_count, partial_count, fail_count, indeterminate_count, average


def post_body(x_text: str, errors: list[str]) -> str:
    marker = "---"
    first = x_text.find(marker)
    if first == -1:
        errors.append("x.md missing opening post boundary '---'")
        return ""
    second = x_text.find(marker, first + len(marker))
    if second == -1:
        errors.append("x.md missing closing post boundary '---'")
        return ""
    return x_text[first + len(marker) : second].strip()


def validate_x_post(
    evaluation_dir: Path,
    cli_name: str,
    findings_text: str,
    errors: list[str],
) -> None:
    x_text = read_text(evaluation_dir / "x.md", errors)
    if not x_text:
        return

    expected_header = f"# X Premium Post — {cli_name}"
    if not x_text.startswith(expected_header):
        errors.append(f"x.md must start with {expected_header!r}")

    if "Copy everything between the lines below into X as one Premium long-form post" not in x_text:
        errors.append("x.md missing template copy instruction comment")

    if "FORMAT RULES" not in x_text:
        errors.append("x.md missing template FORMAT RULES comment")

    if PLACEHOLDER_RE.search(x_text):
        errors.append("x.md contains unreplaced {{PLACEHOLDER}} values")

    body = post_body(x_text, errors)
    if not body:
        return

    body_len = len(body)
    if body_len < 900 or body_len > 1800:
        errors.append(
            f"x.md post body should be 900-1800 characters; found {body_len}"
        )

    first_280 = body[:280]
    for required in (cli_name, "Result:", "Readiness:"):
        if required not in first_280:
            errors.append(f"x.md first 280 chars must include {required!r}")

    if "Full report: [PASTE LINK HERE]" not in body:
        errors.append("x.md missing 'Full report: [PASTE LINK HERE]' line")

    if re.search(r"^\s*\d+/\d+\b", body, re.MULTILINE):
        errors.append("x.md appears to be a numbered thread, not one long-form post")

    pass_count, partial_count, fail_count, indeterminate_count, average = finding_counts(
        findings_text
    )
    n_findings = pass_count + partial_count + fail_count + indeterminate_count
    expected_fragments = [
        f"against {n_findings} Critical CLI Agent Spec",
        f"Result: {average}/3",
    ]
    for fragment in expected_fragments:
        if fragment not in body:
            errors.append(f"x.md missing findings-derived fragment: {fragment!r}")

    forbidden_table_markers = ("|---", "| ---")
    if any(marker in body for marker in forbidden_table_markers):
        errors.append("x.md post body must not contain markdown tables")


def validate_bundle(evaluation_dir: Path, cli_name: str) -> list[str]:
    errors: list[str] = []
    if not evaluation_dir.exists():
        return [f"evaluation directory does not exist: {evaluation_dir}"]
    if not evaluation_dir.is_dir():
        return [f"evaluation path is not a directory: {evaluation_dir}"]

    for filename in REQUIRED_REPORT_FILES:
        path = evaluation_dir / filename
        if not path.exists():
            errors.append(f"missing required file: {path}")

    findings_text = read_text(evaluation_dir / "findings.md", errors)
    if findings_text and not FINDING_ROW_RE.search(findings_text):
        errors.append("findings.md has no parseable score rows")

    validate_x_post(evaluation_dir, cli_name, findings_text, errors)
    return errors


def main(argv: list[str]) -> int:
    require_supported_python()
    args = parse_args(argv)
    evaluation_dir = Path(args.evaluation_dir)
    cli_name = args.cli or evaluation_dir.name

    errors = validate_bundle(evaluation_dir, cli_name)
    if errors:
        print("Report bundle validation FAILED", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1

    print(f"Report bundle validation passed: {evaluation_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
